name: Deploy to Heroku (Backend test)

on:
  push:
    branches:
      - main
    paths:
      - "dev4-persoonlijk-backend/**"
      - ".github/workflows/backend-heroku.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add backend remote origin
        run: git remote add heroku-backend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/dev4-maak-het-persoonlijk.git
      - name: Deploy backend to Heroku
        run: git push heroku-backend `git subtree split --prefix dev4-persoonlijk-backend main`:refs/heads/master --force